#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Pydantic schemas包
"""

from .auth import *
from .common import *
from .server import *
from .deployment import *
from .datasource import *
from .task import *
from .executor import *
from .scheduler import *
from .workflow import *
from .agent import *
from .unified_node import (
    UnifiedNodeType, UnifiedNodeStatus, ExecutionStatus, LogLevel, NodePriority, ErrorHandling,
    UnifiedNodeBase, UnifiedNodeCreate, UnifiedNodeUpdate, UnifiedNodeInDB, UnifiedNodeResponse,
    UnifiedNodeListResponse, UnifiedNodeInstanceBase, UnifiedNodeInstanceCreate,
    UnifiedNodeInstanceUpdate, UnifiedNodeInstanceInDB, UnifiedNodeInstanceResponse,
    UnifiedNodeInstanceListResponse, NodeExecutionBase, NodeExecutionCreate, NodeExecutionUpdate,
    NodeExecutionInDB, NodeExecutionResponse, NodeLogBase, NodeLogCreate, NodeLogInDB,
    NodeLogResponse, NodeLogListResponse, NodeResultBase, NodeResultCreate, NodeResultInDB,
    NodeResultResponse, UnifiedNodeQueryParams, UnifiedNodeInstanceQueryParams,
    NodeExecuteRequest, NodeLogQueryParams, NodeExecutionStats, NodeExecutionStatsListResponse
)

__all__ = [
    # Auth schemas
    "Token",
    "TokenData",
    "UserLogin",
    "UserRegister",
    
    # Common schemas
    "BaseResponse",
    "PaginatedResponse",
    
    # Deployment schemas
    "DeploymentBase",
    "DeploymentCreate",
    "DeploymentUpdate",
    "DeploymentResponse",
    "DeploymentListResponse",
    "DeploymentGPUResponse",
    "DeploymentTemplateResponse",
    "DeploymentTemplateCreate",
    "DeploymentTemplateUpdate",
    
    # Server schemas
    "ServerBase",
    "ServerCreate",
    "ServerUpdate",
    "ServerResponse",
    "ServerListResponse",
    "GPUResourceResponse",
    "ServerStatusResponse",
    "GPUResourceCreate",
    "GPUResourceUpdate",
    "DeploymentServerInfo",
    
    # Datasource schemas
    "DatasourceBase",
    "DatasourceCreate",
    "DatasourceUpdate",
    "DatasourceResponse",
    "DatasourceListResponse",
    "DatasourceTestRequest",
    "DatasourceTestResponse",
    "DatasourceTestLogResponse",
    # "DatasourceUsageStatsResponse",
    "DatasourcePermissionCreate",
    "DatasourcePermissionUpdate",
    "DatasourcePermissionResponse",
    "DatasourceTemplateResponse",
    "DatasourceFilter",
    "DatasourceStats",
    "DatasourceConnectionInfo",
    "DatasourceQueryRequest",
    "DatasourceQueryResponse",
    
    # Task schemas
    "TaskDefinitionBase",
    "TaskDefinitionCreate",
    "TaskDefinitionUpdate",
    "TaskDefinitionResponse",
    "TaskDefinitionListResponse",
    "TaskTemplateBase",
    "TaskTemplateCreate",
    "TaskTemplateUpdate",
    "TaskTemplateResponse",
    "TaskTemplateListResponse",
    "TaskDependencyBase",
    "TaskDependencyCreate",
    "TaskDependencyUpdate",
    "TaskDependencyResponse",
    # Executor schemas
    "GroupType",
    "LoadBalanceStrategy",
    "ExecutorStatus",
    "ExecutorGroupBase",
    "ExecutorGroupCreate",
    "ExecutorGroupUpdate",
    "ExecutorGroupInDB",
    "ExecutorGroup",
    "ExecutorNodeBase",
    "ExecutorNodeCreate",
    "ExecutorNodeUpdate",
    "ExecutorNodeInDB",
    "ExecutorNode",
    "ExecutorNodeHeartbeat",
    "ExecutorNodeStatusUpdate",
    "ExecutorNodeStatus",
    "ClusterHealth",
    "ClusterMetrics",
    "ExecutorGroupQueryParams",
    "ExecutorNodeQueryParams",
    "ExecutorGroupListResponse",
    "ExecutorNodeListResponse",
    
    # Scheduler schemas
    "SchedulerRole",
    "SchedulerStatus",
    "SchedulerNodeBase",
    "SchedulerNodeCreate",
    "SchedulerNodeUpdate",
    "SchedulerNodeInDB",
    "SchedulerNode",
    "SchedulerNodeHeartbeat",
    "SchedulerNodeStatusUpdate",
    "SchedulerClusterStatus",
    "SchedulerLockBase",
    "SchedulerLockCreate",
    "SchedulerLockUpdate",
    "SchedulerLockInDB",
    "SchedulerLock",
    "SchedulerNodeQueryParams",
    "SchedulerLockQueryParams",
    "SchedulerNodeListResponse",
    "SchedulerLockListResponse",
    "TaskScheduleBase",
    "TaskScheduleCreate",
    "TaskScheduleUpdate",
    "TaskScheduleResponse",
    "TaskScheduleListResponse",
    "TaskInstanceBase",
    "TaskInstanceCreate",
    "TaskInstanceUpdate",
    "TaskInstanceResponse",
    "TaskInstanceListResponse",
    "TaskExecutionBase",
    "TaskExecutionUpdate",
    "TaskExecutionResponse",
    "TaskExecutionListResponse",
    "TaskLogBase",
    "TaskLogCreate",
    "TaskLogUpdate",
    "TaskLogResponse",
    "TaskLogListResponse",
    "TaskResultBase",
    "TaskResultCreate",
    "TaskResultUpdate",
    "TaskResultResponse",
    "TaskResultListResponse",
    "TaskQueryParams",
    "TaskStatsResponse",
    
    # Workflow schemas
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowListResponse",
    "WorkflowNodeBase",
    "WorkflowNodeCreate",
    "WorkflowNodeUpdate",
    "WorkflowNodeResponse",
    "WorkflowNodeListResponse",
    "WorkflowConnectionBase",
    "WorkflowConnectionCreate",
    "WorkflowConnectionUpdate",
    "WorkflowConnectionResponse",
    "WorkflowConnectionListResponse",
    "WorkflowInstanceBase",
    "WorkflowInstanceCreate",
    "WorkflowInstanceUpdate",
    "WorkflowInstanceResponse",
    "WorkflowInstanceListResponse",
    "WorkflowNodeInstanceBase",
    "WorkflowNodeInstanceCreate",
    "WorkflowNodeInstanceUpdate",
    "WorkflowNodeInstanceResponse",
    "WorkflowNodeInstanceListResponse",
    "WorkflowScheduleBase",
    "WorkflowScheduleCreate",
    "WorkflowScheduleUpdate",
    "WorkflowScheduleResponse",
    "WorkflowScheduleListResponse",
    "WorkflowQueryParams",
    "WorkflowStatsResponse",
    
    # 统一节点 schemas
    "UnifiedNodeType",
    "UnifiedNodeStatus",
    "ExecutionStatus",
    "LogLevel",
    "NodePriority",
    "ErrorHandling",
    "UnifiedNodeBase",
    "UnifiedNodeCreate",
    "UnifiedNodeUpdate",
    "UnifiedNodeInDB",
    "UnifiedNodeResponse",
    "UnifiedNodeListResponse",
    "UnifiedNodeInstanceBase",
    "UnifiedNodeInstanceCreate",
    "UnifiedNodeInstanceUpdate",
    "UnifiedNodeInstanceInDB",
    "UnifiedNodeInstanceResponse",
    "UnifiedNodeInstanceListResponse",
    "NodeExecutionBase",
    "NodeExecutionCreate",
    "NodeExecutionUpdate",
    "NodeExecutionInDB",
    "NodeExecutionResponse",
    "NodeLogBase",
    "NodeLogCreate",
    "NodeLogInDB",
    "NodeLogResponse",
    "NodeLogListResponse",
    "NodeResultBase",
    "NodeResultCreate",
    "NodeResultInDB",
    "NodeResultResponse",
    "UnifiedNodeQueryParams",
    "UnifiedNodeInstanceQueryParams",
    "NodeExecuteRequest",
    "NodeLogQueryParams",
    "NodeExecutionStats",
    "NodeExecutionStatsListResponse",
    
    # Agent schemas
    "AgentStatus",
    "AgentType",
    "ToolType",
    "AgentBase",
    "AgentCreate",
    "AgentUpdate",
    "AgentInDB",
    "AgentResponse",
    "AgentListItem",
    "AgentListResponse",
    "AgentQueryParams",
    "AgentToolBase",
    "AgentToolCreate",
    "AgentToolUpdate",
    "AgentToolResponse",
    "AgentToolListResponse",
    "AgentConversationBase",
    "AgentConversationCreate",
    "AgentConversationUpdate",
    "AgentConversationResponse",
    "AgentConversationListResponse",
    "AgentMessageBase",
    "AgentMessageCreate",
    "AgentMessageResponse",
    "AgentMessageListResponse",
    "AgentChatRequest",
    "AgentChatResponse",
    "AgentStatsResponse",
    "ModelConfigSchema",
    "MemoryConfigSchema",
    "AgentConfigValidationResponse",
]